server:
  port: 8888

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    url: jdbc:mysql://localhost:3306/pal-help?useUnicode=true&characterEncoding=utf-8mb4&serverTimezone=Asia/Shanghai
    username: root
    password: root